import React from "react";
import Head from "next/head";

import { Router, useRouter } from "next/router";
import Link from "next/link";

const home = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Routing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>index</h1>
      <Link href="/product/">
        <a>product</a>
      </Link>

      <h1
        onClick={() => router.push("/product/")}
        style={{ cursor: "pointer" }}
      >
        go to the next page
      </h1>

      <h1
        onClick={() => router.push("/product/")}
        style={{ cursor: "pointer" }}
      >
        go to the next page usin
      </h1>
    </>
  );
};

export default home;
